// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

/**
 * Protobuf enum {@code depot.devtools.auth.v0.identity.admin.ClientType}
 */
public enum ClientType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CLIENT_TYPE_UNSET = 0;</code>
   */
  CLIENT_TYPE_UNSET(0),
  /**
   * <code>CLIENT_FIRST_PARTY = 1;</code>
   */
  CLIENT_FIRST_PARTY(1),
  /**
   * <code>CLIENT_THIRD_PARTY = 2;</code>
   */
  CLIENT_THIRD_PARTY(2),
  /**
   * <code>CLIENT_SYSTEM_PARTY = 3;</code>
   */
  CLIENT_SYSTEM_PARTY(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CLIENT_TYPE_UNSET = 0;</code>
   */
  public static final int CLIENT_TYPE_UNSET_VALUE = 0;
  /**
   * <code>CLIENT_FIRST_PARTY = 1;</code>
   */
  public static final int CLIENT_FIRST_PARTY_VALUE = 1;
  /**
   * <code>CLIENT_THIRD_PARTY = 2;</code>
   */
  public static final int CLIENT_THIRD_PARTY_VALUE = 2;
  /**
   * <code>CLIENT_SYSTEM_PARTY = 3;</code>
   */
  public static final int CLIENT_SYSTEM_PARTY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ClientType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ClientType forNumber(int value) {
    switch (value) {
      case 0: return CLIENT_TYPE_UNSET;
      case 1: return CLIENT_FIRST_PARTY;
      case 2: return CLIENT_THIRD_PARTY;
      case 3: return CLIENT_SYSTEM_PARTY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ClientType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ClientType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ClientType>() {
          public ClientType findValueByNumber(int number) {
            return ClientType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dev.auth3.identity.admin.AdminProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ClientType[] VALUES = values();

  public static ClientType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ClientType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:depot.devtools.auth.v0.identity.admin.ClientType)
}

