// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

/**
 * Protobuf type {@code depot.devtools.auth.v0.identity.admin.CreateConnectionRequest}
 */
public final class CreateConnectionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:depot.devtools.auth.v0.identity.admin.CreateConnectionRequest)
    CreateConnectionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateConnectionRequest.newBuilder() to construct.
  private CreateConnectionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateConnectionRequest() {
    id_ = "";
    clientId_ = "";
    clientSecret_ = "";
    buttonImageUrl_ = "";
    provider_ = 0;
    oidcDiscoveryUrl_ = "";
    mfa_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    type_ = 0;
    scopes_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateConnectionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateConnectionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            clientId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            clientSecret_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            buttonImageUrl_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            provider_ = rawValue;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            oidcDiscoveryUrl_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              mfa_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            mfa_.add(s);
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            scopes_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        mfa_ = mfa_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.auth3.identity.admin.AdminProto.internal_static_depot_devtools_auth_v0_identity_admin_CreateConnectionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.auth3.identity.admin.AdminProto.internal_static_depot_devtools_auth_v0_identity_admin_CreateConnectionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.auth3.identity.admin.CreateConnectionRequest.class, dev.auth3.identity.admin.CreateConnectionRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers}
   */
  public enum Providers
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>OPENID = 1;</code>
     */
    OPENID(1),
    /**
     * <code>AMAZON = 2;</code>
     */
    AMAZON(2),
    /**
     * <code>BITBUCKET = 3;</code>
     */
    BITBUCKET(3),
    /**
     * <code>BOX = 4;</code>
     */
    BOX(4),
    /**
     * <code>DAILYMOTION = 5;</code>
     */
    DAILYMOTION(5),
    /**
     * <code>DEEZER = 6;</code>
     */
    DEEZER(6),
    /**
     * <code>DIGITALOCEAN = 7;</code>
     */
    DIGITALOCEAN(7),
    /**
     * <code>DISCORD = 8;</code>
     */
    DISCORD(8),
    /**
     * <code>DROPBOX = 9;</code>
     */
    DROPBOX(9),
    /**
     * <code>EVEONLINE = 10;</code>
     */
    EVEONLINE(10),
    /**
     * <code>FACEBOOK = 11;</code>
     */
    FACEBOOK(11),
    /**
     * <code>FITBIT = 12;</code>
     */
    FITBIT(12),
    /**
     * <code>GITEA = 13;</code>
     */
    GITEA(13),
    /**
     * <code>GITHUB = 14;</code>
     */
    GITHUB(14),
    /**
     * <code>GITLAB = 15;</code>
     */
    GITLAB(15),
    /**
     * <code>GOOGLE = 16;</code>
     */
    GOOGLE(16),
    /**
     * <code>SHOPIFY = 18;</code>
     */
    SHOPIFY(18),
    /**
     * <code>SOUNDCLOUD = 19;</code>
     */
    SOUNDCLOUD(19),
    /**
     * <code>SPOTIFY = 20;</code>
     */
    SPOTIFY(20),
    /**
     * <code>STEAM = 21;</code>
     */
    STEAM(21),
    /**
     * <code>STRIPE = 22;</code>
     */
    STRIPE(22),
    /**
     * <code>TWITCH = 23;</code>
     */
    TWITCH(23),
    /**
     * <code>UBER = 24;</code>
     */
    UBER(24),
    /**
     * <code>WEPAY = 25;</code>
     */
    WEPAY(25),
    /**
     * <code>YAHOO = 26;</code>
     */
    YAHOO(26),
    /**
     * <code>YAMMER = 27;</code>
     */
    YAMMER(27),
    /**
     * <code>HEROKU = 28;</code>
     */
    HEROKU(28),
    /**
     * <code>INSTAGRAM = 29;</code>
     */
    INSTAGRAM(29),
    /**
     * <code>INTERCOM = 30;</code>
     */
    INTERCOM(30),
    /**
     * <code>KAKAO = 31;</code>
     */
    KAKAO(31),
    /**
     * <code>LASTFM = 32;</code>
     */
    LASTFM(32),
    /**
     * <code>LINKEDIN = 33;</code>
     */
    LINKEDIN(33),
    /**
     * <code>LINE = 34;</code>
     */
    LINE(34),
    /**
     * <code>ONEDRIVE = 35;</code>
     */
    ONEDRIVE(35),
    /**
     * <code>AZUREAD = 36;</code>
     */
    AZUREAD(36),
    /**
     * <code>MICROSOFTONLINE = 37;</code>
     */
    MICROSOFTONLINE(37),
    /**
     * <code>BATTLENET = 38;</code>
     */
    BATTLENET(38),
    /**
     * <code>PAYPAL = 39;</code>
     */
    PAYPAL(39),
    /**
     * <code>TWITTER = 40;</code>
     */
    TWITTER(40),
    /**
     * <code>SALESFORCE = 41;</code>
     */
    SALESFORCE(41),
    /**
     * <code>TYPETALK = 42;</code>
     */
    TYPETALK(42),
    /**
     * <code>SLACK = 43;</code>
     */
    SLACK(43),
    /**
     * <code>MEETUP = 44;</code>
     */
    MEETUP(44),
    /**
     * <code>XERO = 46;</code>
     */
    XERO(46),
    /**
     * <code>VK = 47;</code>
     */
    VK(47),
    /**
     * <code>NAVER = 48;</code>
     */
    NAVER(48),
    /**
     * <code>YANDEX = 49;</code>
     */
    YANDEX(49),
    /**
     * <code>NEXTCLOUD = 50;</code>
     */
    NEXTCLOUD(50),
    /**
     * <code>APPLE = 52;</code>
     */
    APPLE(52),
    /**
     * <code>STRAVA = 53;</code>
     */
    STRAVA(53),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>OPENID = 1;</code>
     */
    public static final int OPENID_VALUE = 1;
    /**
     * <code>AMAZON = 2;</code>
     */
    public static final int AMAZON_VALUE = 2;
    /**
     * <code>BITBUCKET = 3;</code>
     */
    public static final int BITBUCKET_VALUE = 3;
    /**
     * <code>BOX = 4;</code>
     */
    public static final int BOX_VALUE = 4;
    /**
     * <code>DAILYMOTION = 5;</code>
     */
    public static final int DAILYMOTION_VALUE = 5;
    /**
     * <code>DEEZER = 6;</code>
     */
    public static final int DEEZER_VALUE = 6;
    /**
     * <code>DIGITALOCEAN = 7;</code>
     */
    public static final int DIGITALOCEAN_VALUE = 7;
    /**
     * <code>DISCORD = 8;</code>
     */
    public static final int DISCORD_VALUE = 8;
    /**
     * <code>DROPBOX = 9;</code>
     */
    public static final int DROPBOX_VALUE = 9;
    /**
     * <code>EVEONLINE = 10;</code>
     */
    public static final int EVEONLINE_VALUE = 10;
    /**
     * <code>FACEBOOK = 11;</code>
     */
    public static final int FACEBOOK_VALUE = 11;
    /**
     * <code>FITBIT = 12;</code>
     */
    public static final int FITBIT_VALUE = 12;
    /**
     * <code>GITEA = 13;</code>
     */
    public static final int GITEA_VALUE = 13;
    /**
     * <code>GITHUB = 14;</code>
     */
    public static final int GITHUB_VALUE = 14;
    /**
     * <code>GITLAB = 15;</code>
     */
    public static final int GITLAB_VALUE = 15;
    /**
     * <code>GOOGLE = 16;</code>
     */
    public static final int GOOGLE_VALUE = 16;
    /**
     * <code>SHOPIFY = 18;</code>
     */
    public static final int SHOPIFY_VALUE = 18;
    /**
     * <code>SOUNDCLOUD = 19;</code>
     */
    public static final int SOUNDCLOUD_VALUE = 19;
    /**
     * <code>SPOTIFY = 20;</code>
     */
    public static final int SPOTIFY_VALUE = 20;
    /**
     * <code>STEAM = 21;</code>
     */
    public static final int STEAM_VALUE = 21;
    /**
     * <code>STRIPE = 22;</code>
     */
    public static final int STRIPE_VALUE = 22;
    /**
     * <code>TWITCH = 23;</code>
     */
    public static final int TWITCH_VALUE = 23;
    /**
     * <code>UBER = 24;</code>
     */
    public static final int UBER_VALUE = 24;
    /**
     * <code>WEPAY = 25;</code>
     */
    public static final int WEPAY_VALUE = 25;
    /**
     * <code>YAHOO = 26;</code>
     */
    public static final int YAHOO_VALUE = 26;
    /**
     * <code>YAMMER = 27;</code>
     */
    public static final int YAMMER_VALUE = 27;
    /**
     * <code>HEROKU = 28;</code>
     */
    public static final int HEROKU_VALUE = 28;
    /**
     * <code>INSTAGRAM = 29;</code>
     */
    public static final int INSTAGRAM_VALUE = 29;
    /**
     * <code>INTERCOM = 30;</code>
     */
    public static final int INTERCOM_VALUE = 30;
    /**
     * <code>KAKAO = 31;</code>
     */
    public static final int KAKAO_VALUE = 31;
    /**
     * <code>LASTFM = 32;</code>
     */
    public static final int LASTFM_VALUE = 32;
    /**
     * <code>LINKEDIN = 33;</code>
     */
    public static final int LINKEDIN_VALUE = 33;
    /**
     * <code>LINE = 34;</code>
     */
    public static final int LINE_VALUE = 34;
    /**
     * <code>ONEDRIVE = 35;</code>
     */
    public static final int ONEDRIVE_VALUE = 35;
    /**
     * <code>AZUREAD = 36;</code>
     */
    public static final int AZUREAD_VALUE = 36;
    /**
     * <code>MICROSOFTONLINE = 37;</code>
     */
    public static final int MICROSOFTONLINE_VALUE = 37;
    /**
     * <code>BATTLENET = 38;</code>
     */
    public static final int BATTLENET_VALUE = 38;
    /**
     * <code>PAYPAL = 39;</code>
     */
    public static final int PAYPAL_VALUE = 39;
    /**
     * <code>TWITTER = 40;</code>
     */
    public static final int TWITTER_VALUE = 40;
    /**
     * <code>SALESFORCE = 41;</code>
     */
    public static final int SALESFORCE_VALUE = 41;
    /**
     * <code>TYPETALK = 42;</code>
     */
    public static final int TYPETALK_VALUE = 42;
    /**
     * <code>SLACK = 43;</code>
     */
    public static final int SLACK_VALUE = 43;
    /**
     * <code>MEETUP = 44;</code>
     */
    public static final int MEETUP_VALUE = 44;
    /**
     * <code>XERO = 46;</code>
     */
    public static final int XERO_VALUE = 46;
    /**
     * <code>VK = 47;</code>
     */
    public static final int VK_VALUE = 47;
    /**
     * <code>NAVER = 48;</code>
     */
    public static final int NAVER_VALUE = 48;
    /**
     * <code>YANDEX = 49;</code>
     */
    public static final int YANDEX_VALUE = 49;
    /**
     * <code>NEXTCLOUD = 50;</code>
     */
    public static final int NEXTCLOUD_VALUE = 50;
    /**
     * <code>APPLE = 52;</code>
     */
    public static final int APPLE_VALUE = 52;
    /**
     * <code>STRAVA = 53;</code>
     */
    public static final int STRAVA_VALUE = 53;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Providers valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Providers forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return OPENID;
        case 2: return AMAZON;
        case 3: return BITBUCKET;
        case 4: return BOX;
        case 5: return DAILYMOTION;
        case 6: return DEEZER;
        case 7: return DIGITALOCEAN;
        case 8: return DISCORD;
        case 9: return DROPBOX;
        case 10: return EVEONLINE;
        case 11: return FACEBOOK;
        case 12: return FITBIT;
        case 13: return GITEA;
        case 14: return GITHUB;
        case 15: return GITLAB;
        case 16: return GOOGLE;
        case 18: return SHOPIFY;
        case 19: return SOUNDCLOUD;
        case 20: return SPOTIFY;
        case 21: return STEAM;
        case 22: return STRIPE;
        case 23: return TWITCH;
        case 24: return UBER;
        case 25: return WEPAY;
        case 26: return YAHOO;
        case 27: return YAMMER;
        case 28: return HEROKU;
        case 29: return INSTAGRAM;
        case 30: return INTERCOM;
        case 31: return KAKAO;
        case 32: return LASTFM;
        case 33: return LINKEDIN;
        case 34: return LINE;
        case 35: return ONEDRIVE;
        case 36: return AZUREAD;
        case 37: return MICROSOFTONLINE;
        case 38: return BATTLENET;
        case 39: return PAYPAL;
        case 40: return TWITTER;
        case 41: return SALESFORCE;
        case 42: return TYPETALK;
        case 43: return SLACK;
        case 44: return MEETUP;
        case 46: return XERO;
        case 47: return VK;
        case 48: return NAVER;
        case 49: return YANDEX;
        case 50: return NEXTCLOUD;
        case 52: return APPLE;
        case 53: return STRAVA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Providers>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Providers> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Providers>() {
            public Providers findValueByNumber(int number) {
              return Providers.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dev.auth3.identity.admin.CreateConnectionRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Providers[] VALUES = values();

    public static Providers valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Providers(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers)
  }

  /**
   * Protobuf enum {@code depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types}
   */
  public enum Types
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSET = 0;</code>
     */
    UNSET(0),
    /**
     * <code>PASSWORD = 1;</code>
     */
    PASSWORD(1),
    /**
     * <code>OTP = 2;</code>
     */
    OTP(2),
    /**
     * <code>TOTP = 3;</code>
     */
    TOTP(3),
    /**
     * <code>OIDC = 4;</code>
     */
    OIDC(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSET = 0;</code>
     */
    public static final int UNSET_VALUE = 0;
    /**
     * <code>PASSWORD = 1;</code>
     */
    public static final int PASSWORD_VALUE = 1;
    /**
     * <code>OTP = 2;</code>
     */
    public static final int OTP_VALUE = 2;
    /**
     * <code>TOTP = 3;</code>
     */
    public static final int TOTP_VALUE = 3;
    /**
     * <code>OIDC = 4;</code>
     */
    public static final int OIDC_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Types valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Types forNumber(int value) {
      switch (value) {
        case 0: return UNSET;
        case 1: return PASSWORD;
        case 2: return OTP;
        case 3: return TOTP;
        case 4: return OIDC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Types>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Types> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Types>() {
            public Types findValueByNumber(int number) {
              return Types.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dev.auth3.identity.admin.CreateConnectionRequest.getDescriptor().getEnumTypes().get(1);
    }

    private static final Types[] VALUES = values();

    public static Types valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Types(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1[json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1[json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object clientId_;
  /**
   * <code>string client_id = 2[json_name = "clientId"];</code>
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <code>string client_id = 2[json_name = "clientId"];</code>
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_SECRET_FIELD_NUMBER = 3;
  private volatile java.lang.Object clientSecret_;
  /**
   * <code>string client_secret = 3[json_name = "clientSecret"];</code>
   * @return The clientSecret.
   */
  @java.lang.Override
  public java.lang.String getClientSecret() {
    java.lang.Object ref = clientSecret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientSecret_ = s;
      return s;
    }
  }
  /**
   * <code>string client_secret = 3[json_name = "clientSecret"];</code>
   * @return The bytes for clientSecret.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientSecretBytes() {
    java.lang.Object ref = clientSecret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientSecret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUTTON_IMAGE_URL_FIELD_NUMBER = 4;
  private volatile java.lang.Object buttonImageUrl_;
  /**
   * <code>string button_image_url = 4[json_name = "buttonImageUrl"];</code>
   * @return The buttonImageUrl.
   */
  @java.lang.Override
  public java.lang.String getButtonImageUrl() {
    java.lang.Object ref = buttonImageUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      buttonImageUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string button_image_url = 4[json_name = "buttonImageUrl"];</code>
   * @return The bytes for buttonImageUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getButtonImageUrlBytes() {
    java.lang.Object ref = buttonImageUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buttonImageUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVIDER_FIELD_NUMBER = 6;
  private int provider_;
  /**
   * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers provider = 6[json_name = "provider"];</code>
   * @return The enum numeric value on the wire for provider.
   */
  @java.lang.Override public int getProviderValue() {
    return provider_;
  }
  /**
   * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers provider = 6[json_name = "provider"];</code>
   * @return The provider.
   */
  @java.lang.Override public dev.auth3.identity.admin.CreateConnectionRequest.Providers getProvider() {
    @SuppressWarnings("deprecation")
    dev.auth3.identity.admin.CreateConnectionRequest.Providers result = dev.auth3.identity.admin.CreateConnectionRequest.Providers.valueOf(provider_);
    return result == null ? dev.auth3.identity.admin.CreateConnectionRequest.Providers.UNRECOGNIZED : result;
  }

  public static final int OIDC_DISCOVERY_URL_FIELD_NUMBER = 7;
  private volatile java.lang.Object oidcDiscoveryUrl_;
  /**
   * <code>string oidc_discovery_url = 7[json_name = "oidcDiscoveryUrl"];</code>
   * @return The oidcDiscoveryUrl.
   */
  @java.lang.Override
  public java.lang.String getOidcDiscoveryUrl() {
    java.lang.Object ref = oidcDiscoveryUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      oidcDiscoveryUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string oidc_discovery_url = 7[json_name = "oidcDiscoveryUrl"];</code>
   * @return The bytes for oidcDiscoveryUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOidcDiscoveryUrlBytes() {
    java.lang.Object ref = oidcDiscoveryUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      oidcDiscoveryUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MFA_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList mfa_;
  /**
   * <code>repeated string mfa = 8[json_name = "mfa"];</code>
   * @return A list containing the mfa.
   */
  public com.google.protobuf.ProtocolStringList
      getMfaList() {
    return mfa_;
  }
  /**
   * <code>repeated string mfa = 8[json_name = "mfa"];</code>
   * @return The count of mfa.
   */
  public int getMfaCount() {
    return mfa_.size();
  }
  /**
   * <code>repeated string mfa = 8[json_name = "mfa"];</code>
   * @param index The index of the element to return.
   * @return The mfa at the given index.
   */
  public java.lang.String getMfa(int index) {
    return mfa_.get(index);
  }
  /**
   * <code>repeated string mfa = 8[json_name = "mfa"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the mfa at the given index.
   */
  public com.google.protobuf.ByteString
      getMfaBytes(int index) {
    return mfa_.getByteString(index);
  }

  public static final int TYPE_FIELD_NUMBER = 9;
  private int type_;
  /**
   * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types type = 9[json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types type = 9[json_name = "type"];</code>
   * @return The type.
   */
  @java.lang.Override public dev.auth3.identity.admin.CreateConnectionRequest.Types getType() {
    @SuppressWarnings("deprecation")
    dev.auth3.identity.admin.CreateConnectionRequest.Types result = dev.auth3.identity.admin.CreateConnectionRequest.Types.valueOf(type_);
    return result == null ? dev.auth3.identity.admin.CreateConnectionRequest.Types.UNRECOGNIZED : result;
  }

  public static final int SCOPES_FIELD_NUMBER = 10;
  private volatile java.lang.Object scopes_;
  /**
   * <code>string scopes = 10[json_name = "scopes"];</code>
   * @return The scopes.
   */
  @java.lang.Override
  public java.lang.String getScopes() {
    java.lang.Object ref = scopes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scopes_ = s;
      return s;
    }
  }
  /**
   * <code>string scopes = 10[json_name = "scopes"];</code>
   * @return The bytes for scopes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScopesBytes() {
    java.lang.Object ref = scopes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scopes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getClientIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientId_);
    }
    if (!getClientSecretBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientSecret_);
    }
    if (!getButtonImageUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, buttonImageUrl_);
    }
    if (provider_ != dev.auth3.identity.admin.CreateConnectionRequest.Providers.NONE.getNumber()) {
      output.writeEnum(6, provider_);
    }
    if (!getOidcDiscoveryUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, oidcDiscoveryUrl_);
    }
    for (int i = 0; i < mfa_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, mfa_.getRaw(i));
    }
    if (type_ != dev.auth3.identity.admin.CreateConnectionRequest.Types.UNSET.getNumber()) {
      output.writeEnum(9, type_);
    }
    if (!getScopesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, scopes_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getClientIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientId_);
    }
    if (!getClientSecretBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientSecret_);
    }
    if (!getButtonImageUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, buttonImageUrl_);
    }
    if (provider_ != dev.auth3.identity.admin.CreateConnectionRequest.Providers.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, provider_);
    }
    if (!getOidcDiscoveryUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, oidcDiscoveryUrl_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < mfa_.size(); i++) {
        dataSize += computeStringSizeNoTag(mfa_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMfaList().size();
    }
    if (type_ != dev.auth3.identity.admin.CreateConnectionRequest.Types.UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, type_);
    }
    if (!getScopesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, scopes_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.auth3.identity.admin.CreateConnectionRequest)) {
      return super.equals(obj);
    }
    dev.auth3.identity.admin.CreateConnectionRequest other = (dev.auth3.identity.admin.CreateConnectionRequest) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getClientId()
        .equals(other.getClientId())) return false;
    if (!getClientSecret()
        .equals(other.getClientSecret())) return false;
    if (!getButtonImageUrl()
        .equals(other.getButtonImageUrl())) return false;
    if (provider_ != other.provider_) return false;
    if (!getOidcDiscoveryUrl()
        .equals(other.getOidcDiscoveryUrl())) return false;
    if (!getMfaList()
        .equals(other.getMfaList())) return false;
    if (type_ != other.type_) return false;
    if (!getScopes()
        .equals(other.getScopes())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    hash = (37 * hash) + CLIENT_SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getClientSecret().hashCode();
    hash = (37 * hash) + BUTTON_IMAGE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getButtonImageUrl().hashCode();
    hash = (37 * hash) + PROVIDER_FIELD_NUMBER;
    hash = (53 * hash) + provider_;
    hash = (37 * hash) + OIDC_DISCOVERY_URL_FIELD_NUMBER;
    hash = (53 * hash) + getOidcDiscoveryUrl().hashCode();
    if (getMfaCount() > 0) {
      hash = (37 * hash) + MFA_FIELD_NUMBER;
      hash = (53 * hash) + getMfaList().hashCode();
    }
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + SCOPES_FIELD_NUMBER;
    hash = (53 * hash) + getScopes().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.auth3.identity.admin.CreateConnectionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.auth3.identity.admin.CreateConnectionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.auth3.identity.admin.CreateConnectionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code depot.devtools.auth.v0.identity.admin.CreateConnectionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:depot.devtools.auth.v0.identity.admin.CreateConnectionRequest)
      dev.auth3.identity.admin.CreateConnectionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.auth3.identity.admin.AdminProto.internal_static_depot_devtools_auth_v0_identity_admin_CreateConnectionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.auth3.identity.admin.AdminProto.internal_static_depot_devtools_auth_v0_identity_admin_CreateConnectionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.auth3.identity.admin.CreateConnectionRequest.class, dev.auth3.identity.admin.CreateConnectionRequest.Builder.class);
    }

    // Construct using dev.auth3.identity.admin.CreateConnectionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      clientId_ = "";

      clientSecret_ = "";

      buttonImageUrl_ = "";

      provider_ = 0;

      oidcDiscoveryUrl_ = "";

      mfa_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;

      scopes_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.auth3.identity.admin.AdminProto.internal_static_depot_devtools_auth_v0_identity_admin_CreateConnectionRequest_descriptor;
    }

    @java.lang.Override
    public dev.auth3.identity.admin.CreateConnectionRequest getDefaultInstanceForType() {
      return dev.auth3.identity.admin.CreateConnectionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public dev.auth3.identity.admin.CreateConnectionRequest build() {
      dev.auth3.identity.admin.CreateConnectionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.auth3.identity.admin.CreateConnectionRequest buildPartial() {
      dev.auth3.identity.admin.CreateConnectionRequest result = new dev.auth3.identity.admin.CreateConnectionRequest(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.clientId_ = clientId_;
      result.clientSecret_ = clientSecret_;
      result.buttonImageUrl_ = buttonImageUrl_;
      result.provider_ = provider_;
      result.oidcDiscoveryUrl_ = oidcDiscoveryUrl_;
      if (((bitField0_ & 0x00000001) != 0)) {
        mfa_ = mfa_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.mfa_ = mfa_;
      result.type_ = type_;
      result.scopes_ = scopes_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.auth3.identity.admin.CreateConnectionRequest) {
        return mergeFrom((dev.auth3.identity.admin.CreateConnectionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.auth3.identity.admin.CreateConnectionRequest other) {
      if (other == dev.auth3.identity.admin.CreateConnectionRequest.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        onChanged();
      }
      if (!other.getClientSecret().isEmpty()) {
        clientSecret_ = other.clientSecret_;
        onChanged();
      }
      if (!other.getButtonImageUrl().isEmpty()) {
        buttonImageUrl_ = other.buttonImageUrl_;
        onChanged();
      }
      if (other.provider_ != 0) {
        setProviderValue(other.getProviderValue());
      }
      if (!other.getOidcDiscoveryUrl().isEmpty()) {
        oidcDiscoveryUrl_ = other.oidcDiscoveryUrl_;
        onChanged();
      }
      if (!other.mfa_.isEmpty()) {
        if (mfa_.isEmpty()) {
          mfa_ = other.mfa_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMfaIsMutable();
          mfa_.addAll(other.mfa_);
        }
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getScopes().isEmpty()) {
        scopes_ = other.scopes_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dev.auth3.identity.admin.CreateConnectionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dev.auth3.identity.admin.CreateConnectionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1[json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1[json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1[json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1[json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1[json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clientId_ = "";
    /**
     * <code>string client_id = 2[json_name = "clientId"];</code>
     * @return The clientId.
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_id = 2[json_name = "clientId"];</code>
     * @return The bytes for clientId.
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_id = 2[json_name = "clientId"];</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 2[json_name = "clientId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      
      clientId_ = getDefaultInstance().getClientId();
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 2[json_name = "clientId"];</code>
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clientSecret_ = "";
    /**
     * <code>string client_secret = 3[json_name = "clientSecret"];</code>
     * @return The clientSecret.
     */
    public java.lang.String getClientSecret() {
      java.lang.Object ref = clientSecret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientSecret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_secret = 3[json_name = "clientSecret"];</code>
     * @return The bytes for clientSecret.
     */
    public com.google.protobuf.ByteString
        getClientSecretBytes() {
      java.lang.Object ref = clientSecret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_secret = 3[json_name = "clientSecret"];</code>
     * @param value The clientSecret to set.
     * @return This builder for chaining.
     */
    public Builder setClientSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientSecret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string client_secret = 3[json_name = "clientSecret"];</code>
     * @return This builder for chaining.
     */
    public Builder clearClientSecret() {
      
      clientSecret_ = getDefaultInstance().getClientSecret();
      onChanged();
      return this;
    }
    /**
     * <code>string client_secret = 3[json_name = "clientSecret"];</code>
     * @param value The bytes for clientSecret to set.
     * @return This builder for chaining.
     */
    public Builder setClientSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientSecret_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object buttonImageUrl_ = "";
    /**
     * <code>string button_image_url = 4[json_name = "buttonImageUrl"];</code>
     * @return The buttonImageUrl.
     */
    public java.lang.String getButtonImageUrl() {
      java.lang.Object ref = buttonImageUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buttonImageUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string button_image_url = 4[json_name = "buttonImageUrl"];</code>
     * @return The bytes for buttonImageUrl.
     */
    public com.google.protobuf.ByteString
        getButtonImageUrlBytes() {
      java.lang.Object ref = buttonImageUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buttonImageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string button_image_url = 4[json_name = "buttonImageUrl"];</code>
     * @param value The buttonImageUrl to set.
     * @return This builder for chaining.
     */
    public Builder setButtonImageUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      buttonImageUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string button_image_url = 4[json_name = "buttonImageUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearButtonImageUrl() {
      
      buttonImageUrl_ = getDefaultInstance().getButtonImageUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string button_image_url = 4[json_name = "buttonImageUrl"];</code>
     * @param value The bytes for buttonImageUrl to set.
     * @return This builder for chaining.
     */
    public Builder setButtonImageUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      buttonImageUrl_ = value;
      onChanged();
      return this;
    }

    private int provider_ = 0;
    /**
     * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers provider = 6[json_name = "provider"];</code>
     * @return The enum numeric value on the wire for provider.
     */
    @java.lang.Override public int getProviderValue() {
      return provider_;
    }
    /**
     * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers provider = 6[json_name = "provider"];</code>
     * @param value The enum numeric value on the wire for provider to set.
     * @return This builder for chaining.
     */
    public Builder setProviderValue(int value) {
      
      provider_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers provider = 6[json_name = "provider"];</code>
     * @return The provider.
     */
    @java.lang.Override
    public dev.auth3.identity.admin.CreateConnectionRequest.Providers getProvider() {
      @SuppressWarnings("deprecation")
      dev.auth3.identity.admin.CreateConnectionRequest.Providers result = dev.auth3.identity.admin.CreateConnectionRequest.Providers.valueOf(provider_);
      return result == null ? dev.auth3.identity.admin.CreateConnectionRequest.Providers.UNRECOGNIZED : result;
    }
    /**
     * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers provider = 6[json_name = "provider"];</code>
     * @param value The provider to set.
     * @return This builder for chaining.
     */
    public Builder setProvider(dev.auth3.identity.admin.CreateConnectionRequest.Providers value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      provider_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers provider = 6[json_name = "provider"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProvider() {
      
      provider_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object oidcDiscoveryUrl_ = "";
    /**
     * <code>string oidc_discovery_url = 7[json_name = "oidcDiscoveryUrl"];</code>
     * @return The oidcDiscoveryUrl.
     */
    public java.lang.String getOidcDiscoveryUrl() {
      java.lang.Object ref = oidcDiscoveryUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oidcDiscoveryUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string oidc_discovery_url = 7[json_name = "oidcDiscoveryUrl"];</code>
     * @return The bytes for oidcDiscoveryUrl.
     */
    public com.google.protobuf.ByteString
        getOidcDiscoveryUrlBytes() {
      java.lang.Object ref = oidcDiscoveryUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oidcDiscoveryUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string oidc_discovery_url = 7[json_name = "oidcDiscoveryUrl"];</code>
     * @param value The oidcDiscoveryUrl to set.
     * @return This builder for chaining.
     */
    public Builder setOidcDiscoveryUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      oidcDiscoveryUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string oidc_discovery_url = 7[json_name = "oidcDiscoveryUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOidcDiscoveryUrl() {
      
      oidcDiscoveryUrl_ = getDefaultInstance().getOidcDiscoveryUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string oidc_discovery_url = 7[json_name = "oidcDiscoveryUrl"];</code>
     * @param value The bytes for oidcDiscoveryUrl to set.
     * @return This builder for chaining.
     */
    public Builder setOidcDiscoveryUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      oidcDiscoveryUrl_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList mfa_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMfaIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        mfa_ = new com.google.protobuf.LazyStringArrayList(mfa_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @return A list containing the mfa.
     */
    public com.google.protobuf.ProtocolStringList
        getMfaList() {
      return mfa_.getUnmodifiableView();
    }
    /**
     * <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @return The count of mfa.
     */
    public int getMfaCount() {
      return mfa_.size();
    }
    /**
     * <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @param index The index of the element to return.
     * @return The mfa at the given index.
     */
    public java.lang.String getMfa(int index) {
      return mfa_.get(index);
    }
    /**
     * <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the mfa at the given index.
     */
    public com.google.protobuf.ByteString
        getMfaBytes(int index) {
      return mfa_.getByteString(index);
    }
    /**
     * <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @param index The index to set the value at.
     * @param value The mfa to set.
     * @return This builder for chaining.
     */
    public Builder setMfa(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMfaIsMutable();
      mfa_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @param value The mfa to add.
     * @return This builder for chaining.
     */
    public Builder addMfa(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMfaIsMutable();
      mfa_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @param values The mfa to add.
     * @return This builder for chaining.
     */
    public Builder addAllMfa(
        java.lang.Iterable<java.lang.String> values) {
      ensureMfaIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, mfa_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMfa() {
      mfa_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @param value The bytes of the mfa to add.
     * @return This builder for chaining.
     */
    public Builder addMfaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMfaIsMutable();
      mfa_.add(value);
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types type = 9[json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types type = 9[json_name = "type"];</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types type = 9[json_name = "type"];</code>
     * @return The type.
     */
    @java.lang.Override
    public dev.auth3.identity.admin.CreateConnectionRequest.Types getType() {
      @SuppressWarnings("deprecation")
      dev.auth3.identity.admin.CreateConnectionRequest.Types result = dev.auth3.identity.admin.CreateConnectionRequest.Types.valueOf(type_);
      return result == null ? dev.auth3.identity.admin.CreateConnectionRequest.Types.UNRECOGNIZED : result;
    }
    /**
     * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types type = 9[json_name = "type"];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(dev.auth3.identity.admin.CreateConnectionRequest.Types value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types type = 9[json_name = "type"];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object scopes_ = "";
    /**
     * <code>string scopes = 10[json_name = "scopes"];</code>
     * @return The scopes.
     */
    public java.lang.String getScopes() {
      java.lang.Object ref = scopes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scopes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scopes = 10[json_name = "scopes"];</code>
     * @return The bytes for scopes.
     */
    public com.google.protobuf.ByteString
        getScopesBytes() {
      java.lang.Object ref = scopes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scopes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scopes = 10[json_name = "scopes"];</code>
     * @param value The scopes to set.
     * @return This builder for chaining.
     */
    public Builder setScopes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scopes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string scopes = 10[json_name = "scopes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearScopes() {
      
      scopes_ = getDefaultInstance().getScopes();
      onChanged();
      return this;
    }
    /**
     * <code>string scopes = 10[json_name = "scopes"];</code>
     * @param value The bytes for scopes to set.
     * @return This builder for chaining.
     */
    public Builder setScopesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scopes_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:depot.devtools.auth.v0.identity.admin.CreateConnectionRequest)
  }

  // @@protoc_insertion_point(class_scope:depot.devtools.auth.v0.identity.admin.CreateConnectionRequest)
  private static final dev.auth3.identity.admin.CreateConnectionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.auth3.identity.admin.CreateConnectionRequest();
  }

  public static dev.auth3.identity.admin.CreateConnectionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateConnectionRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateConnectionRequest>() {
    @java.lang.Override
    public CreateConnectionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateConnectionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateConnectionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateConnectionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.auth3.identity.admin.CreateConnectionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

