// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

public interface GetAddressRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:depot.devtools.auth.v0.identity.admin.GetAddressRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1[json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1[json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string verification = 2[json_name = "verification"];</code>
   * @return The verification.
   */
  java.lang.String getVerification();
  /**
   * <code>string verification = 2[json_name = "verification"];</code>
   * @return The bytes for verification.
   */
  com.google.protobuf.ByteString
      getVerificationBytes();

  public dev.auth3.identity.admin.GetAddressRequest.MatchCase getMatchCase();
}
