// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

public interface GetAddressesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:depot.devtools.auth.v0.identity.admin.GetAddressesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address addresses = 1[json_name = "addresses"];</code>
   */
  java.util.List<dev.auth3.identity.admin.GetAddressesResponse.Address> 
      getAddressesList();
  /**
   * <code>repeated .depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address addresses = 1[json_name = "addresses"];</code>
   */
  dev.auth3.identity.admin.GetAddressesResponse.Address getAddresses(int index);
  /**
   * <code>repeated .depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address addresses = 1[json_name = "addresses"];</code>
   */
  int getAddressesCount();
  /**
   * <code>repeated .depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address addresses = 1[json_name = "addresses"];</code>
   */
  java.util.List<? extends dev.auth3.identity.admin.GetAddressesResponse.AddressOrBuilder> 
      getAddressesOrBuilderList();
  /**
   * <code>repeated .depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address addresses = 1[json_name = "addresses"];</code>
   */
  dev.auth3.identity.admin.GetAddressesResponse.AddressOrBuilder getAddressesOrBuilder(
      int index);
}
