// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

public interface GetIdentityByIdentifierResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:depot.devtools.auth.v0.identity.admin.GetIdentityByIdentifierResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.depot.devtools.auth.v0.identity.admin.GetIdentityByIdentifierResponse.Identity identity = 1[json_name = "identity"];</code>
   * @return Whether the identity field is set.
   */
  boolean hasIdentity();
  /**
   * <code>.depot.devtools.auth.v0.identity.admin.GetIdentityByIdentifierResponse.Identity identity = 1[json_name = "identity"];</code>
   * @return The identity.
   */
  dev.auth3.identity.admin.GetIdentityByIdentifierResponse.Identity getIdentity();
  /**
   * <code>.depot.devtools.auth.v0.identity.admin.GetIdentityByIdentifierResponse.Identity identity = 1[json_name = "identity"];</code>
   */
  dev.auth3.identity.admin.GetIdentityByIdentifierResponse.IdentityOrBuilder getIdentityOrBuilder();
}
