// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

public interface GetProfileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:depot.devtools.auth.v0.identity.admin.GetProfileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string profile = 1[json_name = "profile"];</code>
   * @return The profile.
   */
  java.lang.String getProfile();
  /**
   * <code>string profile = 1[json_name = "profile"];</code>
   * @return The bytes for profile.
   */
  com.google.protobuf.ByteString
      getProfileBytes();
}
