// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

/**
 * Protobuf type {@code depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest}
 */
public final class GetUserBaseStatisticsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest)
    GetUserBaseStatisticsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetUserBaseStatisticsRequest.newBuilder() to construct.
  private GetUserBaseStatisticsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetUserBaseStatisticsRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetUserBaseStatisticsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetUserBaseStatisticsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            daysBefore_ = input.readUInt32();
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lifetimeStartAt_ != null) {
              subBuilder = lifetimeStartAt_.toBuilder();
            }
            lifetimeStartAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lifetimeStartAt_);
              lifetimeStartAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lifetimeEndAt_ != null) {
              subBuilder = lifetimeEndAt_.toBuilder();
            }
            lifetimeEndAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lifetimeEndAt_);
              lifetimeEndAt_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.auth3.identity.admin.AdminProto.internal_static_depot_devtools_auth_v0_identity_admin_GetUserBaseStatisticsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.auth3.identity.admin.AdminProto.internal_static_depot_devtools_auth_v0_identity_admin_GetUserBaseStatisticsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.auth3.identity.admin.GetUserBaseStatisticsRequest.class, dev.auth3.identity.admin.GetUserBaseStatisticsRequest.Builder.class);
  }

  public static final int DAYS_BEFORE_FIELD_NUMBER = 1;
  private int daysBefore_;
  /**
   * <code>uint32 days_before = 1[json_name = "daysBefore"];</code>
   * @return The daysBefore.
   */
  @java.lang.Override
  public int getDaysBefore() {
    return daysBefore_;
  }

  public static final int LIFETIME_START_AT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp lifetimeStartAt_;
  /**
   * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
   * @return Whether the lifetimeStartAt field is set.
   */
  @java.lang.Override
  public boolean hasLifetimeStartAt() {
    return lifetimeStartAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
   * @return The lifetimeStartAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLifetimeStartAt() {
    return lifetimeStartAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lifetimeStartAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLifetimeStartAtOrBuilder() {
    return getLifetimeStartAt();
  }

  public static final int LIFETIME_END_AT_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp lifetimeEndAt_;
  /**
   * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
   * @return Whether the lifetimeEndAt field is set.
   */
  @java.lang.Override
  public boolean hasLifetimeEndAt() {
    return lifetimeEndAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
   * @return The lifetimeEndAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLifetimeEndAt() {
    return lifetimeEndAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lifetimeEndAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLifetimeEndAtOrBuilder() {
    return getLifetimeEndAt();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (daysBefore_ != 0) {
      output.writeUInt32(1, daysBefore_);
    }
    if (lifetimeStartAt_ != null) {
      output.writeMessage(2, getLifetimeStartAt());
    }
    if (lifetimeEndAt_ != null) {
      output.writeMessage(3, getLifetimeEndAt());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (daysBefore_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, daysBefore_);
    }
    if (lifetimeStartAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLifetimeStartAt());
    }
    if (lifetimeEndAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLifetimeEndAt());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.auth3.identity.admin.GetUserBaseStatisticsRequest)) {
      return super.equals(obj);
    }
    dev.auth3.identity.admin.GetUserBaseStatisticsRequest other = (dev.auth3.identity.admin.GetUserBaseStatisticsRequest) obj;

    if (getDaysBefore()
        != other.getDaysBefore()) return false;
    if (hasLifetimeStartAt() != other.hasLifetimeStartAt()) return false;
    if (hasLifetimeStartAt()) {
      if (!getLifetimeStartAt()
          .equals(other.getLifetimeStartAt())) return false;
    }
    if (hasLifetimeEndAt() != other.hasLifetimeEndAt()) return false;
    if (hasLifetimeEndAt()) {
      if (!getLifetimeEndAt()
          .equals(other.getLifetimeEndAt())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DAYS_BEFORE_FIELD_NUMBER;
    hash = (53 * hash) + getDaysBefore();
    if (hasLifetimeStartAt()) {
      hash = (37 * hash) + LIFETIME_START_AT_FIELD_NUMBER;
      hash = (53 * hash) + getLifetimeStartAt().hashCode();
    }
    if (hasLifetimeEndAt()) {
      hash = (37 * hash) + LIFETIME_END_AT_FIELD_NUMBER;
      hash = (53 * hash) + getLifetimeEndAt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.auth3.identity.admin.GetUserBaseStatisticsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest)
      dev.auth3.identity.admin.GetUserBaseStatisticsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.auth3.identity.admin.AdminProto.internal_static_depot_devtools_auth_v0_identity_admin_GetUserBaseStatisticsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.auth3.identity.admin.AdminProto.internal_static_depot_devtools_auth_v0_identity_admin_GetUserBaseStatisticsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.auth3.identity.admin.GetUserBaseStatisticsRequest.class, dev.auth3.identity.admin.GetUserBaseStatisticsRequest.Builder.class);
    }

    // Construct using dev.auth3.identity.admin.GetUserBaseStatisticsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      daysBefore_ = 0;

      if (lifetimeStartAtBuilder_ == null) {
        lifetimeStartAt_ = null;
      } else {
        lifetimeStartAt_ = null;
        lifetimeStartAtBuilder_ = null;
      }
      if (lifetimeEndAtBuilder_ == null) {
        lifetimeEndAt_ = null;
      } else {
        lifetimeEndAt_ = null;
        lifetimeEndAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.auth3.identity.admin.AdminProto.internal_static_depot_devtools_auth_v0_identity_admin_GetUserBaseStatisticsRequest_descriptor;
    }

    @java.lang.Override
    public dev.auth3.identity.admin.GetUserBaseStatisticsRequest getDefaultInstanceForType() {
      return dev.auth3.identity.admin.GetUserBaseStatisticsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public dev.auth3.identity.admin.GetUserBaseStatisticsRequest build() {
      dev.auth3.identity.admin.GetUserBaseStatisticsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.auth3.identity.admin.GetUserBaseStatisticsRequest buildPartial() {
      dev.auth3.identity.admin.GetUserBaseStatisticsRequest result = new dev.auth3.identity.admin.GetUserBaseStatisticsRequest(this);
      result.daysBefore_ = daysBefore_;
      if (lifetimeStartAtBuilder_ == null) {
        result.lifetimeStartAt_ = lifetimeStartAt_;
      } else {
        result.lifetimeStartAt_ = lifetimeStartAtBuilder_.build();
      }
      if (lifetimeEndAtBuilder_ == null) {
        result.lifetimeEndAt_ = lifetimeEndAt_;
      } else {
        result.lifetimeEndAt_ = lifetimeEndAtBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.auth3.identity.admin.GetUserBaseStatisticsRequest) {
        return mergeFrom((dev.auth3.identity.admin.GetUserBaseStatisticsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.auth3.identity.admin.GetUserBaseStatisticsRequest other) {
      if (other == dev.auth3.identity.admin.GetUserBaseStatisticsRequest.getDefaultInstance()) return this;
      if (other.getDaysBefore() != 0) {
        setDaysBefore(other.getDaysBefore());
      }
      if (other.hasLifetimeStartAt()) {
        mergeLifetimeStartAt(other.getLifetimeStartAt());
      }
      if (other.hasLifetimeEndAt()) {
        mergeLifetimeEndAt(other.getLifetimeEndAt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dev.auth3.identity.admin.GetUserBaseStatisticsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dev.auth3.identity.admin.GetUserBaseStatisticsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int daysBefore_ ;
    /**
     * <code>uint32 days_before = 1[json_name = "daysBefore"];</code>
     * @return The daysBefore.
     */
    @java.lang.Override
    public int getDaysBefore() {
      return daysBefore_;
    }
    /**
     * <code>uint32 days_before = 1[json_name = "daysBefore"];</code>
     * @param value The daysBefore to set.
     * @return This builder for chaining.
     */
    public Builder setDaysBefore(int value) {
      
      daysBefore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 days_before = 1[json_name = "daysBefore"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDaysBefore() {
      
      daysBefore_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp lifetimeStartAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lifetimeStartAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     * @return Whether the lifetimeStartAt field is set.
     */
    public boolean hasLifetimeStartAt() {
      return lifetimeStartAtBuilder_ != null || lifetimeStartAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     * @return The lifetimeStartAt.
     */
    public com.google.protobuf.Timestamp getLifetimeStartAt() {
      if (lifetimeStartAtBuilder_ == null) {
        return lifetimeStartAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lifetimeStartAt_;
      } else {
        return lifetimeStartAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     */
    public Builder setLifetimeStartAt(com.google.protobuf.Timestamp value) {
      if (lifetimeStartAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lifetimeStartAt_ = value;
        onChanged();
      } else {
        lifetimeStartAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     */
    public Builder setLifetimeStartAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lifetimeStartAtBuilder_ == null) {
        lifetimeStartAt_ = builderForValue.build();
        onChanged();
      } else {
        lifetimeStartAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     */
    public Builder mergeLifetimeStartAt(com.google.protobuf.Timestamp value) {
      if (lifetimeStartAtBuilder_ == null) {
        if (lifetimeStartAt_ != null) {
          lifetimeStartAt_ =
            com.google.protobuf.Timestamp.newBuilder(lifetimeStartAt_).mergeFrom(value).buildPartial();
        } else {
          lifetimeStartAt_ = value;
        }
        onChanged();
      } else {
        lifetimeStartAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     */
    public Builder clearLifetimeStartAt() {
      if (lifetimeStartAtBuilder_ == null) {
        lifetimeStartAt_ = null;
        onChanged();
      } else {
        lifetimeStartAt_ = null;
        lifetimeStartAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getLifetimeStartAtBuilder() {
      
      onChanged();
      return getLifetimeStartAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLifetimeStartAtOrBuilder() {
      if (lifetimeStartAtBuilder_ != null) {
        return lifetimeStartAtBuilder_.getMessageOrBuilder();
      } else {
        return lifetimeStartAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lifetimeStartAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLifetimeStartAtFieldBuilder() {
      if (lifetimeStartAtBuilder_ == null) {
        lifetimeStartAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLifetimeStartAt(),
                getParentForChildren(),
                isClean());
        lifetimeStartAt_ = null;
      }
      return lifetimeStartAtBuilder_;
    }

    private com.google.protobuf.Timestamp lifetimeEndAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lifetimeEndAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     * @return Whether the lifetimeEndAt field is set.
     */
    public boolean hasLifetimeEndAt() {
      return lifetimeEndAtBuilder_ != null || lifetimeEndAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     * @return The lifetimeEndAt.
     */
    public com.google.protobuf.Timestamp getLifetimeEndAt() {
      if (lifetimeEndAtBuilder_ == null) {
        return lifetimeEndAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lifetimeEndAt_;
      } else {
        return lifetimeEndAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     */
    public Builder setLifetimeEndAt(com.google.protobuf.Timestamp value) {
      if (lifetimeEndAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lifetimeEndAt_ = value;
        onChanged();
      } else {
        lifetimeEndAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     */
    public Builder setLifetimeEndAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lifetimeEndAtBuilder_ == null) {
        lifetimeEndAt_ = builderForValue.build();
        onChanged();
      } else {
        lifetimeEndAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     */
    public Builder mergeLifetimeEndAt(com.google.protobuf.Timestamp value) {
      if (lifetimeEndAtBuilder_ == null) {
        if (lifetimeEndAt_ != null) {
          lifetimeEndAt_ =
            com.google.protobuf.Timestamp.newBuilder(lifetimeEndAt_).mergeFrom(value).buildPartial();
        } else {
          lifetimeEndAt_ = value;
        }
        onChanged();
      } else {
        lifetimeEndAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     */
    public Builder clearLifetimeEndAt() {
      if (lifetimeEndAtBuilder_ == null) {
        lifetimeEndAt_ = null;
        onChanged();
      } else {
        lifetimeEndAt_ = null;
        lifetimeEndAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getLifetimeEndAtBuilder() {
      
      onChanged();
      return getLifetimeEndAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLifetimeEndAtOrBuilder() {
      if (lifetimeEndAtBuilder_ != null) {
        return lifetimeEndAtBuilder_.getMessageOrBuilder();
      } else {
        return lifetimeEndAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lifetimeEndAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLifetimeEndAtFieldBuilder() {
      if (lifetimeEndAtBuilder_ == null) {
        lifetimeEndAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLifetimeEndAt(),
                getParentForChildren(),
                isClean());
        lifetimeEndAt_ = null;
      }
      return lifetimeEndAtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest)
  }

  // @@protoc_insertion_point(class_scope:depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest)
  private static final dev.auth3.identity.admin.GetUserBaseStatisticsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.auth3.identity.admin.GetUserBaseStatisticsRequest();
  }

  public static dev.auth3.identity.admin.GetUserBaseStatisticsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUserBaseStatisticsRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetUserBaseStatisticsRequest>() {
    @java.lang.Override
    public GetUserBaseStatisticsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetUserBaseStatisticsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetUserBaseStatisticsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUserBaseStatisticsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.auth3.identity.admin.GetUserBaseStatisticsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

