// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

/**
 * Protobuf enum {@code depot.devtools.auth.v0.identity.admin.SubjectType}
 */
public enum SubjectType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUBJECT_TYPE_PUBLIC = 0;</code>
   */
  SUBJECT_TYPE_PUBLIC(0),
  /**
   * <code>SUBJECT_TYPE_PAIRWISE = 1;</code>
   */
  SUBJECT_TYPE_PAIRWISE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SUBJECT_TYPE_PUBLIC = 0;</code>
   */
  public static final int SUBJECT_TYPE_PUBLIC_VALUE = 0;
  /**
   * <code>SUBJECT_TYPE_PAIRWISE = 1;</code>
   */
  public static final int SUBJECT_TYPE_PAIRWISE_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SubjectType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SubjectType forNumber(int value) {
    switch (value) {
      case 0: return SUBJECT_TYPE_PUBLIC;
      case 1: return SUBJECT_TYPE_PAIRWISE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SubjectType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SubjectType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SubjectType>() {
          public SubjectType findValueByNumber(int number) {
            return SubjectType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dev.auth3.identity.admin.AdminProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final SubjectType[] VALUES = values();

  public static SubjectType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SubjectType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:depot.devtools.auth.v0.identity.admin.SubjectType)
}

