// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

/**
 * Protobuf enum {@code depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg}
 */
public enum TokenEndpointAuthSigningAlg
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET = 0;</code>
   */
  TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET(0),
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256 = 1;</code>
   */
  TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256(1),
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384 = 2;</code>
   */
  TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384(2),
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512 = 3;</code>
   */
  TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512(3),
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256 = 4;</code>
   */
  TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256(4),
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384 = 5;</code>
   */
  TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384(5),
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512 = 6;</code>
   */
  TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512(6),
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256 = 7;</code>
   */
  TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256(7),
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384 = 8;</code>
   */
  TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384(8),
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512 = 9;</code>
   */
  TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET = 0;</code>
   */
  public static final int TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET_VALUE = 0;
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256 = 1;</code>
   */
  public static final int TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256_VALUE = 1;
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384 = 2;</code>
   */
  public static final int TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384_VALUE = 2;
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512 = 3;</code>
   */
  public static final int TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512_VALUE = 3;
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256 = 4;</code>
   */
  public static final int TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256_VALUE = 4;
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384 = 5;</code>
   */
  public static final int TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384_VALUE = 5;
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512 = 6;</code>
   */
  public static final int TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512_VALUE = 6;
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256 = 7;</code>
   */
  public static final int TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256_VALUE = 7;
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384 = 8;</code>
   */
  public static final int TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384_VALUE = 8;
  /**
   * <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512 = 9;</code>
   */
  public static final int TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TokenEndpointAuthSigningAlg valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TokenEndpointAuthSigningAlg forNumber(int value) {
    switch (value) {
      case 0: return TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET;
      case 1: return TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256;
      case 2: return TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384;
      case 3: return TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512;
      case 4: return TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256;
      case 5: return TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384;
      case 6: return TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512;
      case 7: return TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256;
      case 8: return TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384;
      case 9: return TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TokenEndpointAuthSigningAlg>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TokenEndpointAuthSigningAlg> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TokenEndpointAuthSigningAlg>() {
          public TokenEndpointAuthSigningAlg findValueByNumber(int number) {
            return TokenEndpointAuthSigningAlg.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dev.auth3.identity.admin.AdminProto.getDescriptor().getEnumTypes().get(3);
  }

  private static final TokenEndpointAuthSigningAlg[] VALUES = values();

  public static TokenEndpointAuthSigningAlg valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TokenEndpointAuthSigningAlg(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg)
}

