// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

public interface UpdateProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:depot.devtools.auth.v0.identity.admin.UpdateProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string identity_id = 1[json_name = "identityId"];</code>
   * @return The identityId.
   */
  java.lang.String getIdentityId();
  /**
   * <code>string identity_id = 1[json_name = "identityId"];</code>
   * @return The bytes for identityId.
   */
  com.google.protobuf.ByteString
      getIdentityIdBytes();

  /**
   * <code>string profile = 2[json_name = "profile"];</code>
   * @return The profile.
   */
  java.lang.String getProfile();
  /**
   * <code>string profile = 2[json_name = "profile"];</code>
   * @return The bytes for profile.
   */
  com.google.protobuf.ByteString
      getProfileBytes();
}
