// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

public interface UpdateCredentialRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:depot.devtools.auth.v0.identity.admin.UpdateCredentialRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Struct data = 1[json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Struct data = 1[json_name = "data"];</code>
   * @return The data.
   */
  com.google.protobuf.Struct getData();
  /**
   * <code>.google.protobuf.Struct data = 1[json_name = "data"];</code>
   */
  com.google.protobuf.StructOrBuilder getDataOrBuilder();

  /**
   * <code>string connection_id = 2[json_name = "connectionId"];</code>
   * @return The connectionId.
   */
  java.lang.String getConnectionId();
  /**
   * <code>string connection_id = 2[json_name = "connectionId"];</code>
   * @return The bytes for connectionId.
   */
  com.google.protobuf.ByteString
      getConnectionIdBytes();

  /**
   * <code>string identity_id = 3[json_name = "identityId"];</code>
   * @return The identityId.
   */
  java.lang.String getIdentityId();
  /**
   * <code>string identity_id = 3[json_name = "identityId"];</code>
   * @return The bytes for identityId.
   */
  com.google.protobuf.ByteString
      getIdentityIdBytes();
}
