// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity/admin/admin.proto

package dev.auth3.identity.admin;

/**
 * Protobuf enum {@code depot.devtools.auth.v0.identity.admin.UserinfoSignedResponseAlg}
 */
public enum UserinfoSignedResponseAlg
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>USERINFO_SIGNED_RESPONSE_ALG_UNSET = 0;</code>
   */
  USERINFO_SIGNED_RESPONSE_ALG_UNSET(0),
  /**
   * <code>USERINFO_SIGNED_RESPONSE_ALG_NONE = 1;</code>
   */
  USERINFO_SIGNED_RESPONSE_ALG_NONE(1),
  /**
   * <code>USERINFO_SIGNED_RESPONSE_ALG_RS256 = 2;</code>
   */
  USERINFO_SIGNED_RESPONSE_ALG_RS256(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>USERINFO_SIGNED_RESPONSE_ALG_UNSET = 0;</code>
   */
  public static final int USERINFO_SIGNED_RESPONSE_ALG_UNSET_VALUE = 0;
  /**
   * <code>USERINFO_SIGNED_RESPONSE_ALG_NONE = 1;</code>
   */
  public static final int USERINFO_SIGNED_RESPONSE_ALG_NONE_VALUE = 1;
  /**
   * <code>USERINFO_SIGNED_RESPONSE_ALG_RS256 = 2;</code>
   */
  public static final int USERINFO_SIGNED_RESPONSE_ALG_RS256_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static UserinfoSignedResponseAlg valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static UserinfoSignedResponseAlg forNumber(int value) {
    switch (value) {
      case 0: return USERINFO_SIGNED_RESPONSE_ALG_UNSET;
      case 1: return USERINFO_SIGNED_RESPONSE_ALG_NONE;
      case 2: return USERINFO_SIGNED_RESPONSE_ALG_RS256;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<UserinfoSignedResponseAlg>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      UserinfoSignedResponseAlg> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<UserinfoSignedResponseAlg>() {
          public UserinfoSignedResponseAlg findValueByNumber(int number) {
            return UserinfoSignedResponseAlg.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dev.auth3.identity.admin.AdminProto.getDescriptor().getEnumTypes().get(7);
  }

  private static final UserinfoSignedResponseAlg[] VALUES = values();

  public static UserinfoSignedResponseAlg valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private UserinfoSignedResponseAlg(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:depot.devtools.auth.v0.identity.admin.UserinfoSignedResponseAlg)
}

